### ISSUE TITLE
Apple news 更新

### ISSUE THREAD

**Issue by wangxin6** [ShadowsSide/Apple-News#1]
#APPLE NEWS
DOMAIN-SUFFIX,news-events.apple.com,Proxy
DOMAIN-SUFFIX,news-edge.apple.com,Proxy
DOMAIN-SUFFIX,apple.comscoreresearch.com,Proxy
DOMAIN-SUFFIX,play.itunes.apple.com,Proxy
DOMAIN-SUFFIX,play-cdn.itunes-apple.com.akadns.net,Proxy
DOMAIN-SUFFIX,ls.apple.com,Proxy
DOMAIN-SUFFIX,cvws.apple-dns.net,Proxy
DOMAIN-SUFFIX,news.apple-dns.net,Proxy
DOMAIN-SUFFIX,gateway.fe.apple-dns.net,Proxy
DOMAIN-SUFFIX,akamaiedge.net,Proxy
DOMAIN-SUFFIX,gs-loc.apple.com,Proxy
DOMAIN-SUFFIX,bag.itunes.apple.com,Proxy
DOMAIN-SUFFIX,apple.news,Proxy
DOMAIN-SUFFIX,news.iadsdk.apple.com,Proxy

**Comment by ShadowsSide** [comment]
谢谢你的提供🌹，稍后将加入教程中.

wangxin6 <notifications@github.com>于2020年9月18日 周五下午4:51写道：
