### ISSUE TITLE
mac怎么设置分流求助

### ISSUE THREAD

**Issue by CooperHash** [ShadowsSide/Apple-News#11]
如题所示，已经捣鼓很久了没有眉目，救救

**Comment by CooperHash** [comment]
请问是在外部规则集里放icloud proxy list的文件名吗

**Comment by CooperHash** [comment]
map的高德地图字样打开了全局proxy没有消失

**Comment by ShadowsSide** [comment]
是哪个软件？

**Comment by CooperHash** [comment]
surge

**Comment by ShadowsSide** [comment]
https://github.com/ShadowsSide/Apple-News#-%E5%88%86%E6%B5%81%E5%9C%B0%E5%9D%80
