### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by BayAreaLX** [ShadowsSide/Apple-News#3]
surge添加规则那里没弄清楚，可以详细说一下具体步骤么，可以发红包

**Comment by ShadowsSide** [comment]
> surge添加规则那里没弄清楚，可以详细说一下具体步骤么，可以发红包

https://t.me/GodlyGroup
进群组给你解答.

**Comment by ShadowsSide** [comment]
> surge添加规则那里没弄清楚，可以详细说一下具体步骤么，可以发红包

点击主界面出站模式里的"代理规则" > 新增 > 增加规则集 > 选中外部规则集然后选中你想要的策略组，并在下方粘帖Surge的规则地址即可.

**Comment by BayAreaLX** [comment]
太棒了，终于成功了，感谢老哥，新年快乐，以后可以搞一个赞赏，肯定参与哈哈

**Comment by ShadowsSide** [comment]
新年快乐! 谢谢你的肯定.
