### ISSUE TITLE
使用Surge 总是无法成功，使用⭕X 就很好，没有出现过问题，Surge多次检查过设置，麻烦解答一下

### ISSUE THREAD

**Issue by FAST0888** [ShadowsSide/Apple-News#4]

**Comment by FAST0888** [comment]
Surge 规则里是DOMAIN-SUFFIX 不能解析吗？看了你的readme ⭕X 是使用Host

**Comment by ShadowsSide** [comment]
> Surge 规则里是DOMAIN-SUFFIX 不能解析吗？看了你的readme ⭕X 是使用Host  

是否尝试过添加 apple.list 后还是不行？

**Comment by FAST0888** [comment]
一直都有apple.list，规则很全！但是⭕X 跟Surge使用的规则一样

**Comment by ShadowsSide** [comment]
> 一直都有apple.list，规则很全！但是⭕X 跟Surge使用的规则一样

到最近请求查看一下 策略组的走向 是否正确.
